name: Build and Test Action

on: [push]

jobs:
    build:
        name: Build Action
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Npm setup
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
              with:
                  node-version: 24.10.0
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Build action
              run: npm run build

            - name: Upload action artifact
              uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
              with:
                  name: action-dist
                  path: dist

    test:
        name: Test Action
        runs-on: ubuntu-latest
        needs: build

        strategy:
            max-parallel: 1
            matrix:
                include:
                    - ref: ${{ github.ref }}
                      fail_on_warning: false
                    - ref: "__default__"
                      fail_on_warning: false
                    - ref: |
                          - ${{ github.ref }}
                          - ${{ github.ref }}
                      fail_on_warning: false
                    - ref: "[${{ github.ref }}, ${{ github.ref }}]"
                      fail_on_warning: false
                    - ref: "__default__"
                      fail_on_warning: true

        permissions:
            actions: write

        steps:
            - name: Create test file
              run: |
                  mkdir -p test-cache
                  echo "Creating cache for ${{ github.ref }} on ${{ github.sha }} for job ${{ strategy.job-index }}" > test-cache/test.txt

            - name: Create cache
              uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: test-cache
                  key: test-cache-${{ github.run_id }}-${{ strategy.job-index }}

            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
              with:
                  sparse-checkout: action.yml

            - name: Download action artifact
              uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
              with:
                  name: action-dist
                  path: dist

            - name: Run test case (with ref)
              if: matrix.ref != '__default__'
              uses: ./
              continue-on-error: ${{ matrix.fail_on_warning }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ matrix.ref }}
                  fail-on-warning: ${{ matrix.fail_on_warning }}

            - name: Run test case (without ref)
              if: matrix.ref == '__default__'
              uses: ./
              continue-on-error: ${{ matrix.fail_on_warning }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  fail-on-warning: ${{ matrix.fail_on_warning }}

            - name: Try to restore cache
              id: restore-cache
              uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: test-cache
                  key: test-cache-${{ github.run_id }}-${{ strategy.job-index }}

            - name: Verify cache deletion
              run: |
                  if [ ${{ steps.restore-cache.outputs.cache-hit }} ]; then
                      echo "Cache was not deleted properly."
                      exit 1
                  else
                      echo "Cache deletion verified."
                  fi

    commit-build:
        name: Commit Action Build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: test

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Download action artifact
              uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
              with:
                  name: action-dist
                  path: dist

            - name: Commit dist directory
              if: github.ref == 'refs/heads/main'
              uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
              with:
                  commit_message: "📦 Update action build [skip ci]"
                  file_pattern: "dist/**"
