name: Build and Test Action

on: [push]

jobs:
    build:
        name: Build Action
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Npm setup
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
              with:
                  node-version: 24.10.0
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build action
              run: npm run build

            - name: Upload action artifact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
              with:
                  name: action-dist
                  path: dist

    prepare-test:
        name: Prepare Test Caches
        runs-on: ubuntu-latest

        steps:
            - name: Create test file
              run: |
                  mkdir -p test-cache
                  echo "Creating cache for ${{ github.ref }} on ${{ github.sha }}" > test-cache/test.txt

            - name: Create cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: test-cache
                  key: test-cache-${{ github.run_id }}

    test:
        name: Test Action
        runs-on: ubuntu-latest
        needs: [build, prepare-test]

        permissions:
            actions: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Download action artifact
              uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
              with:
                  name: action-dist
                  path: dist

            - name: Delete current branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.ref }}

            - name: Delete default branch caches
              uses: ./

            - name: Delete list branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: |
                      - refs/heads/branch-1
                      - refs/heads/branch-2

            - name: Delete list inline branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: "[refs/heads/branch-1, refs/heads/branch-2]"

            - name: Delete caches with fail-on-warning
              uses: ./
              with:
                  fail-on-warning: true

    commit-build:
        name: Commit Action Build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: test

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Download action artifact
              uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
              with:
                  name: action-dist
                  path: dist

            - name: Commit dist directory
              if: github.ref == 'refs/heads/main'
              uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
              with:
                  commit_message: "📦 Update action build [skip ci]"
                  file_pattern: "dist/**"
