name: Test Action

on: [push]

jobs:
    create-cache:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Create test file
              run: |
                  mkdir -p test-cache
                  echo "Creating cache for ${{ github.ref }} on ${{ github.sha }}" > test-cache/test.txt

            - name: Create cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: test-cache
                  key: test-cache-${{ github.run_id }}

    delete-cache:
        runs-on: ubuntu-latest
        needs: create-cache

        permissions:
            actions: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Install dependencies
              run: npm ci

            - name: Build action
              run: npm run build

            - name: Delete current branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.ref }}

            - name: Delete default branch caches
              uses: ./

            - name: Delete list branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: |
                      - refs/heads/branch-1
                      - refs/heads/branch-2

            - name: Delete list inline branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: "[refs/heads/branch-1, refs/heads/branch-2]"

            - name: Delete caches with fail-on-warning
              uses: ./
              with:
                  fail-on-warning: true

            - name: Commit dist directory
              if: github.ref == 'refs/heads/main'
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "📦 Update action build [skip ci]"
                  file_pattern: "dist/**"
