name: Enforce conventions

on:
  pull_request:
    types: [opened]

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-conventions.yml@05474ed1ebbcf4bb351086c6a2469443a252f392 # v1.2.3
    permissions:
      pull-requests: write
