name: Enforce conventions

on:
  pull_request:
    types: [opened]

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-conventions.yml@704b29288880186b96bda072068735a8a7c9e112 # v1.2.1
    permissions:
      pull-requests: write
