name: Sync labels

on:
    schedule:
      - cron: "0 3 * * *"
    push:
        branches: [main]
        paths: [.github/workflows/sync-labels.yml]
    workflow_dispatch:

jobs:
    run:
        uses: Friedinger/Configs/.github/workflows/action-sync-labels.yml@main
        permissions:
            issues: write
