name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-sync-labels.yml@5e54d461aa22d24a54550e10c7784a262c4dd925 # main
    permissions:
      issues: write
