name: Test Action

on: [push]

jobs:
    create-cache:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create test file
              run: |
                  mkdir -p test-cache
                  echo "Creating cache for ${{ github.ref }} on ${{ github.sha }}" > test-cache/test.txt

            - name: Create cache
              uses: actions/cache@v4
              with:
                  path: test-cache
                  key: test-cache-${{ github.run_id }}

    delete-cache:
        runs-on: ubuntu-latest
        needs: create-cache

        permissions:
            actions: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Delete current branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.ref }}

            - name: Delete default branch caches
              uses: ./

            - name: Delete list branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: |
                      - refs/heads/branch-1
                      - refs/heads/branch-2

            - name: Delete list inline branch caches
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  ref: "[refs/heads/branch-1, refs/heads/branch-2]"

            - name: Delete caches with fail-on-warning
              uses: ./
              with:
                  fail-on-warning: true
