name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create test file
        run: |
          mkdir -p test-cache
          echo "Test hash: ${{ github.sha }}" > test-cache/test.txt

      - name: Create cache
        uses: actions/cache@v4
        with:
          path: test-cache
          key: test-cache-${{ github.run_id }}

      - name: Delete branch caches
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
